name: .NET CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Instalar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restaurar dependencias API
        run: dotnet restore Mundial2026API/Mundial2026API/Mundial2026API.csproj

      - name: Restaurar dependencias Tests
        run: dotnet restore Mundial2026API/Mundial2026API.Tests/Mundial2026API.Tests.csproj

      - name: Compilar API
        run: dotnet build Mundial2026API/Mundial2026API/Mundial2026API.csproj --no-restore --configuration Release

      - name: Compilar Tests
        run: dotnet build Mundial2026API/Mundial2026API.Tests/Mundial2026API.Tests.csproj --no-restore --configuration Release

      - name: Ejecutar tests
        run: dotnet test Mundial2026API/Mundial2026API.Tests/Mundial2026API.Tests.csproj --no-build --configuration Release --verbosity normal